== How to run the application ==

The application is started using maven wrapper.
To run the application start it up

On Windows: ./mvnw.cmd spring-boot:run

On Linux or MacOs: ./mvnw spring-boot:run

== Application description ==
The service layer abstraction is used to provide two presentation layers.
The first presentation layer is an api (controller.api package), the second one
is a web Thymeleaf-based GUI (controller.gui package).

Database operations performed with Hibernate.
    *Address of console http://localhost:8080/h2-console/
    *Access login "sa" without password

Application uses Thymeleaf templates.

All layers tested with Junit and Mockito.

Front-end part tested with Selenium.
    *Using Firefox driver

There is starter data in data.sql
    *two planets
    *one master owning planet
    *one master without planet

== How to use GUI ==
There are masters list and masters operation menu by the address http://localhost:8080/gui/masters
There are planets list and planets operation menu by the address http://localhost:8080/gui/planets
GUI uses navigation layout.
GUI can handle incorrect inputs
   *Two masters with similar names can't exist
   *Two planets with similar names can't exist
   *Names must begin with letter







