spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    resources: # Static resources
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
#server:
#  servlet:
#    context-path=/api/v1: